Examen-war/src/java/managedbean/QuestionsController.java
package managedbean;

import entities.Questions;
import managedbean.util.JsfUtil;
import managedbean.util.PaginationHelper;
import sessions.QuestionsFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("questionsController")
@SessionScoped
public class QuestionsController implements Serializable {

    private Questions current;
    private DataModel items = null;
    @EJB
    private QuestionsFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public QuestionsController() {
    }

    public Questions getSelected() {
        if (current == null) {
            current = new Questions();
            selectedItemIndex = -1;
        }
        return current;
    }

    private QuestionsFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(100000) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Questions) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Questions();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("QuestionsCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Questions) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("QuestionsUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Questions) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("QuestionsDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Questions getQuestions(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Questions.class)
    public static class QuestionsControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            QuestionsController controller = (QuestionsController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "questionsController");
            return controller.getQuestions(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Questions) {
                Questions o = (Questions) object;
                return getStringKey(o.getIdQuestions());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Questions.class.getName());
            }
        }

    }

}

Examen-war/web/jsf/questions/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateQuestionsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateQuestionsLabel_idQuestions}" for="idQuestions" />
                    <h:inputText id="idQuestions" value="#{questionsController.selected.idQuestions}" title="#{bundle.CreateQuestionsTitle_idQuestions}" required="true" requiredMessage="#{bundle.CreateQuestionsRequiredMessage_idQuestions}"/>
                    <h:outputLabel value="#{bundle.CreateQuestionsLabel_question}" for="question" />
                    <h:inputText id="question" value="#{questionsController.selected.question}" title="#{bundle.CreateQuestionsTitle_question}" required="true" requiredMessage="#{bundle.CreateQuestionsRequiredMessage_question}"/>
                    <h:outputLabel value="#{bundle.CreateQuestionsLabel_consigne}" for="consigne" />
                    <h:inputText id="consigne" value="#{questionsController.selected.consigne}" title="#{bundle.CreateQuestionsTitle_consigne}" />
                    <h:outputLabel value="#{bundle.CreateQuestionsLabel_idExamen}" for="idExamen" />
                    <h:selectOneMenu id="idExamen" value="#{questionsController.selected.idExamen}" title="#{bundle.CreateQuestionsTitle_idExamen}" required="true" requiredMessage="#{bundle.CreateQuestionsRequiredMessage_idExamen}">
                        <f:selectItems value="#{examensController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{questionsController.create}" value="#{bundle.CreateQuestionsSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{questionsController.prepareList}" value="#{bundle.CreateQuestionsShowAllLink}" immediate="true"/>
                <br />
                <br />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Examen-war/web/jsf/questions/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditQuestionsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditQuestionsLabel_idQuestions}" for="idQuestions" />
                    <h:inputText id="idQuestions" value="#{questionsController.selected.idQuestions}" title="#{bundle.EditQuestionsTitle_idQuestions}" required="true" requiredMessage="#{bundle.EditQuestionsRequiredMessage_idQuestions}"/>
                    <h:outputLabel value="#{bundle.EditQuestionsLabel_question}" for="question" />
                    <h:inputText id="question" value="#{questionsController.selected.question}" title="#{bundle.EditQuestionsTitle_question}" required="true" requiredMessage="#{bundle.EditQuestionsRequiredMessage_question}"/>
                    <h:outputLabel value="#{bundle.EditQuestionsLabel_consigne}" for="consigne" />
                    <h:inputText id="consigne" value="#{questionsController.selected.consigne}" title="#{bundle.EditQuestionsTitle_consigne}" />
                    <h:outputLabel value="#{bundle.EditQuestionsLabel_idExamen}" for="idExamen" />
                    <h:selectOneMenu id="idExamen" value="#{questionsController.selected.idExamen}" title="#{bundle.EditQuestionsTitle_idExamen}" required="true" requiredMessage="#{bundle.EditQuestionsRequiredMessage_idExamen}">
                        <f:selectItems value="#{examensController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{questionsController.update}" value="#{bundle.EditQuestionsSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditQuestionsViewLink}"/>
                <br />
                <h:commandLink action="#{questionsController.prepareList}" value="#{bundle.EditQuestionsShowAllLink}" immediate="true"/>
                <br />
                <br />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Examen-war/web/jsf/questions/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListQuestionsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <p:dataTable value="#{questionsController.items}" paginator="true" rows="10" var="item" style="border:solid 1px">
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListQuestionsTitle_idQuestions}"/>
                        </f:facet>
                        <h:outputText value="#{item.idQuestions}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListQuestionsTitle_question}"/>
                        </f:facet>
                        <h:outputText value="#{item.question}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListQuestionsTitle_consigne}"/>
                        </f:facet>
                        <h:outputText value="#{item.consigne}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListQuestionsTitle_idExamen}"/>
                        </f:facet>
                        <h:outputText value="#{item.idExamen}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="&nbsp;"/>
                        </f:facet>
                        <h:commandLink action="#{questionsController.prepareView}" value="#{bundle.ListQuestionsViewLink}"/>
                        <h:outputText value=" "/>
                        <h:commandLink action="#{questionsController.prepareEdit}" value="#{bundle.ListQuestionsEditLink}"/>
                        <h:outputText value=" "/>
                        <h:commandLink action="#{questionsController.destroy}" value="#{bundle.ListQuestionsDestroyLink}"/>
                    </p:column>
                </p:dataTable>
                <br />
                <h:commandLink action="#{questionsController.prepareCreate}" value="#{bundle.ListQuestionsCreateLink}"/>
                <br />
                <br />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Examen-war/web/jsf/questions/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewQuestionsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewQuestionsLabel_idQuestions}"/>
                    <h:outputText value="#{questionsController.selected.idQuestions}" title="#{bundle.ViewQuestionsTitle_idQuestions}"/>
                    <h:outputText value="#{bundle.ViewQuestionsLabel_question}"/>
                    <h:outputText value="#{questionsController.selected.question}" title="#{bundle.ViewQuestionsTitle_question}"/>
                    <h:outputText value="#{bundle.ViewQuestionsLabel_consigne}"/>
                    <h:outputText value="#{questionsController.selected.consigne}" title="#{bundle.ViewQuestionsTitle_consigne}"/>
                    <h:outputText value="#{bundle.ViewQuestionsLabel_idExamen}"/>
                    <h:outputText value="#{questionsController.selected.idExamen}" title="#{bundle.ViewQuestionsTitle_idExamen}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{questionsController.destroyAndView}" value="#{bundle.ViewQuestionsDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewQuestionsEditLink}"/>
                <br />
                <h:commandLink action="#{questionsController.prepareCreate}" value="#{bundle.ViewQuestionsCreateLink}" />
                <br />
                <h:commandLink action="#{questionsController.prepareList}" value="#{bundle.ViewQuestionsShowAllLink}"/>
                <br />
                <br />

            </h:form>
        </ui:define>
    </ui:composition>

</html>