Examen-war/src/java/managedbean/EtudiantsController.java
package managedbean;

import entities.Etudiants;
import managedbean.util.JsfUtil;
import managedbean.util.PaginationHelper;
import sessions.EtudiantsFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("etudiantsController")
@SessionScoped
public class EtudiantsController implements Serializable {

    private Etudiants current;
    private DataModel items = null;
    @EJB
    private EtudiantsFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    private String email;

    public EtudiantsController() {
    }
    public String Authentification(String email , String password)    {
        
        if(ejbFacade.Login(email, password)==true)     
            return "template";
        else return "error";
        
    }

    public Etudiants getSelected() {
        if (current == null) {
            current = new Etudiants();
            selectedItemIndex = -1;
        }
        return current;
    }

    private EtudiantsFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(1000000) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Etudiants) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Etudiants();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("EtudiantsCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Etudiants) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("EtudiantsUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Etudiants) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("EtudiantsDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Etudiants getEtudiants(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Etudiants.class)
    public static class EtudiantsControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            EtudiantsController controller = (EtudiantsController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "etudiantsController");
            return controller.getEtudiants(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Etudiants) {
                Etudiants o = (Etudiants) object;
                return getStringKey(o.getMatricule());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Etudiants.class.getName());
            }
        }

    }

}

Examen-war/web/jsf/etudiants/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateEtudiantsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateEtudiantsLabel_matricule}" for="matricule" />
                    <h:inputText id="matricule" value="#{etudiantsController.selected.matricule}" title="#{bundle.CreateEtudiantsTitle_matricule}" required="true" requiredMessage="#{bundle.CreateEtudiantsRequiredMessage_matricule}"/>
                    <h:outputLabel value="#{bundle.CreateEtudiantsLabel_nom}" for="nom" />
                    <h:inputText id="nom" value="#{etudiantsController.selected.nom}" title="#{bundle.CreateEtudiantsTitle_nom}" required="true" requiredMessage="#{bundle.CreateEtudiantsRequiredMessage_nom}"/>
                    <h:outputLabel value="#{bundle.CreateEtudiantsLabel_prenom}" for="prenom" />
                    <h:inputText id="prenom" value="#{etudiantsController.selected.prenom}" title="#{bundle.CreateEtudiantsTitle_prenom}" required="true" requiredMessage="#{bundle.CreateEtudiantsRequiredMessage_prenom}"/>
                    <h:outputLabel value="#{bundle.CreateEtudiantsLabel_email}" for="email" />
                    <h:inputText id="email" value="#{etudiantsController.selected.email}" title="#{bundle.CreateEtudiantsTitle_email}" required="true" requiredMessage="#{bundle.CreateEtudiantsRequiredMessage_email}"/>
                    <h:outputLabel value="#{bundle.CreateEtudiantsLabel_password}" for="password" />
                    <h:inputText id="password" value="#{etudiantsController.selected.password}" title="#{bundle.CreateEtudiantsTitle_password}" required="true" requiredMessage="#{bundle.CreateEtudiantsRequiredMessage_password}"/>
                    <h:outputLabel value="#{bundle.CreateEtudiantsLabel_note}" for="note" />
                    <h:inputText id="note" value="#{etudiantsController.selected.note}" title="#{bundle.CreateEtudiantsTitle_note}" />
                </h:panelGrid>
                <br />
                <h:commandLink action="#{etudiantsController.create}" value="#{bundle.CreateEtudiantsSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{etudiantsController.prepareList}" value="#{bundle.CreateEtudiantsShowAllLink}" immediate="true"/>
                <br />
                <br />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Examen-war/web/jsf/etudiants/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditEtudiantsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditEtudiantsLabel_matricule}" for="matricule" />
                    <h:inputText id="matricule" value="#{etudiantsController.selected.matricule}" title="#{bundle.EditEtudiantsTitle_matricule}" required="true" requiredMessage="#{bundle.EditEtudiantsRequiredMessage_matricule}"/>
                    <h:outputLabel value="#{bundle.EditEtudiantsLabel_nom}" for="nom" />
                    <h:inputText id="nom" value="#{etudiantsController.selected.nom}" title="#{bundle.EditEtudiantsTitle_nom}" required="true" requiredMessage="#{bundle.EditEtudiantsRequiredMessage_nom}"/>
                    <h:outputLabel value="#{bundle.EditEtudiantsLabel_prenom}" for="prenom" />
                    <h:inputText id="prenom" value="#{etudiantsController.selected.prenom}" title="#{bundle.EditEtudiantsTitle_prenom}" required="true" requiredMessage="#{bundle.EditEtudiantsRequiredMessage_prenom}"/>
                    <h:outputLabel value="#{bundle.EditEtudiantsLabel_email}" for="email" />
                    <h:inputText id="email" value="#{etudiantsController.selected.email}" title="#{bundle.EditEtudiantsTitle_email}" required="true" requiredMessage="#{bundle.EditEtudiantsRequiredMessage_email}"/>
                    <h:outputLabel value="#{bundle.EditEtudiantsLabel_password}" for="password" />
                    <h:inputText id="password" value="#{etudiantsController.selected.password}" title="#{bundle.EditEtudiantsTitle_password}" required="true" requiredMessage="#{bundle.EditEtudiantsRequiredMessage_password}"/>
                    <h:outputLabel value="#{bundle.EditEtudiantsLabel_note}" for="note" />
                    <h:inputText id="note" value="#{etudiantsController.selected.note}" title="#{bundle.EditEtudiantsTitle_note}" />
                </h:panelGrid>
                <h:commandLink action="#{etudiantsController.update}" value="#{bundle.EditEtudiantsSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditEtudiantsViewLink}"/>
                <br />
                <h:commandLink action="#{etudiantsController.prepareList}" value="#{bundle.EditEtudiantsShowAllLink}" immediate="true"/>
                <br />
                <br />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Examen-war/web/jsf/etudiants/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListEtudiantsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListEtudiantsEmpty}" rendered="#{etudiantsController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{etudiantsController.items.rowCount > 0}">
                    <h:outputText value="#{etudiantsController.pagination.pageFirstItem + 1}..#{etudiantsController.pagination.pageLastItem + 1}/#{etudiantsController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{etudiantsController.previous}" value="#{bundle.Previous} #{etudiantsController.pagination.pageSize}" rendered="#{etudiantsController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{etudiantsController.next}" value="#{bundle.Next} #{etudiantsController.pagination.pageSize}" rendered="#{etudiantsController.pagination.hasNextPage}"/>&nbsp;
                    <p:dataTable value="#{etudiantsController.items}" var="item"  style="border:solid 1px">
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEtudiantsTitle_matricule}"/>
                            </f:facet>
                            <h:outputText value="#{item.matricule}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEtudiantsTitle_nom}"/>
                            </f:facet>
                            <h:outputText value="#{item.nom}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEtudiantsTitle_prenom}"/>
                            </f:facet>
                            <h:outputText value="#{item.prenom}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEtudiantsTitle_email}"/>
                            </f:facet>
                            <h:outputText value="#{item.email}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEtudiantsTitle_password}"/>
                            </f:facet>
                            <h:outputText value="#{item.password}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEtudiantsTitle_note}"/>
                            </f:facet>
                            <h:outputText value="#{item.note}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{etudiantsController.prepareView}" value="#{bundle.ListEtudiantsViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{etudiantsController.prepareEdit}" value="#{bundle.ListEtudiantsEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{etudiantsController.destroy}" value="#{bundle.ListEtudiantsDestroyLink}"/>
                        </p:column>
                    </p:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{etudiantsController.prepareCreate}" value="#{bundle.ListEtudiantsCreateLink}"/>
                <br />
                <br />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Examen-war/web/jsf/etudiants/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewEtudiantsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewEtudiantsLabel_matricule}"/>
                    <h:outputText value="#{etudiantsController.selected.matricule}" title="#{bundle.ViewEtudiantsTitle_matricule}"/>
                    <h:outputText value="#{bundle.ViewEtudiantsLabel_nom}"/>
                    <h:outputText value="#{etudiantsController.selected.nom}" title="#{bundle.ViewEtudiantsTitle_nom}"/>
                    <h:outputText value="#{bundle.ViewEtudiantsLabel_prenom}"/>
                    <h:outputText value="#{etudiantsController.selected.prenom}" title="#{bundle.ViewEtudiantsTitle_prenom}"/>
                    <h:outputText value="#{bundle.ViewEtudiantsLabel_email}"/>
                    <h:outputText value="#{etudiantsController.selected.email}" title="#{bundle.ViewEtudiantsTitle_email}"/>
                    <h:outputText value="#{bundle.ViewEtudiantsLabel_password}"/>
                    <h:outputText value="#{etudiantsController.selected.password}" title="#{bundle.ViewEtudiantsTitle_password}"/>
                    <h:outputText value="#{bundle.ViewEtudiantsLabel_note}"/>
                    <h:outputText value="#{etudiantsController.selected.note}" title="#{bundle.ViewEtudiantsTitle_note}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{etudiantsController.destroyAndView}" value="#{bundle.ViewEtudiantsDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewEtudiantsEditLink}"/>
                <br />
                <h:commandLink action="#{etudiantsController.prepareCreate}" value="#{bundle.ViewEtudiantsCreateLink}" />
                <br />
                <h:commandLink action="#{etudiantsController.prepareList}" value="#{bundle.ViewEtudiantsShowAllLink}"/>
                <br />
                <br />

            </h:form>
        </ui:define>
    </ui:composition>

</html>