Examen-war/src/java/ExamenManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import entities.Questions;
import entities.Reponses;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import sessions.EtudiantsFacade;
import sessions.QuestionsFacade;
import sessions.ReponsesFacade;

/**
 *
 * @author Hajar MDD
 */
@Named(value = "examenManagedBean")
@SessionScoped
public class ExamenManagedBean implements Serializable {

     private List<Questions> questionlist;
     private List<Reponses> reponseslist;
@EJB
private QuestionsFacade questionfacade ; 
@EJB
    private ReponsesFacade reponsesfacade;
    /**
     * Creates a new instance of ProduitManagedBean
     */
    public ExamenManagedBean() {
    }
    public List<Questions> getQuestions() {
    return questionfacade.findAll()  ; 
    }
    
    public String showDetails(int id){
    
    return "Reponces?idQuestion="+id ; 
    }
    
}

Examen-war/web/ListExam.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        
    </h:body>
</html>

Examen-war/web/Login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Bienvenue</title>
    </h:head>
    <h:body>
        <h1>Login</h1>
        <h:message for="email" />
                    <h:message for="password" />
        <f:view>
             

            <h:form>
                
                <h:panelGrid columns="2">
                   
                    
                   <p:outputLabel value="Email:" for="email" />
                    <p:inputText id="email"  value="#{email}" title="Email" required="true" requiredMessage="The Email field is required."/>
                    <p:outputLabel value="Password:" for="password" />
                    <p:inputText id="password"  value="#{password}" title="Password" required="true" requiredMessage="The Password field is required."/>
                </h:panelGrid>
                <p:commandButton value="Login" action="#{etudiantsController.Authentification(email,password)}"></p:commandButton>
            </h:form>
        </f:view>

    </h:body>
</html>

Examen-war/web/Questionexam.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <f:view>


            <h:form>
                <h1><h:outputText value="List"/></h1>
                <p:dataTable value="#{examenManagedBean.questions}" var="item" paginator="true" rows="1">
                    
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Question"/>
                        </f:facet>
                        <h:outputText value="#{item.question}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Consigne"/>
                        </f:facet>
                        <h:outputText value="#{item.consigne}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Reponces pour cette question "/>
                        </f:facet>
                        <h:outputText value="#{item.idQuestions}"/>
                        <h:link outcome="#{examenManagedBean.showDetails(item.idQuestions)}" value="#{item.idQuestions}"> Voir reponces </h:link>
                   
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Repondre a une question  "/>
                        </f:facet>


                        <h:form>
                            <h1><h:outputText value="Repondre"/></h1>
                            <p:panelGrid columns="2">
                                   <p:outputLabel value="Reponse:" for="reponse" />
                                <p:inputText id="reponse" value="#{reponsesController.selected.reponse}" title="Reponse" required="true" requiredMessage="The Reponse field is required."/>
                                </p:panelGrid>
                                <p:commandButton value="Valider" action="#{reponsesController.Authentification(reponse,IdQuestion)}"></p:commandButton>
            
                        </h:form>

                    </p:column>
                    
                    
                </p:dataTable>
            </h:form>
        </f:view>


    </h:body>
</html>

Examen-war/web/Reponces.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
  
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <f:view>


            <h:form>
                <h1><h:outputText value="List"/></h1>
                <p:dataTable value="#{reponsesController.reponces}" var="item" >
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="IdReponse"/>
                        </f:facet>
                        <h:outputText value="#{item.idReponse}"/>
                    </p:column>
                  
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Reponse"/>
                        </f:facet>
                        <h:outputText value="#{item.reponse}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="IsBonneReponse"/>
                        </f:facet>
                        <h:outputText value="#{item.isBonneReponse}"/>
                    </p:column>
                </p:dataTable>
            </h:form>
        </f:view>

    </h:body>
</html>

Examen-war/web/error.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Error</title>
    </h:head>
    <h:body>
        <h5>Erreur d'Authentification !</h5>
        <h:link value="try again" outcome="Login"></h:link>
    </h:body>
</html>

Examen-war/web/passerExamen.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
    <f:metadata>
        <f:viewParam name="idExam" value="#{passerExamenManagedBean.idExam}" required="true" />
        <f:viewAction action="#{passerExamenManagedBean.load()}" />
    </f:metadata>
    <h:head>
        <title>Passer examen</title>
	<h:outputStylesheet library="css" name="jsfcrud.css"/>
    </h:head>
    <h:body>
	<h3>Examen</h3>
	<h:form>
	    <p:panelGrid columns="2">
		<h:outputText value="#{bundle.ViewExamensLabel_nom}"/>
		<h:outputText value="#{passerExamenManagedBean.examen.nom}" title="#{bundle.ViewExamensTitle_nom}"/>
		<h:outputText value="#{bundle.ViewExamensLabel_matiere}"/>
		<h:outputText value="#{passerExamenManagedBean.examen.matiere}" title="#{bundle.ViewExamensTitle_matiere}"/>
	    </p:panelGrid>
	</h:form>

	<h5>Question</h5>
	<h:form>
	    <p:panelGrid columns="2">
		<h:outputText value="#{bundle.ViewQuestionsLabel_question}"/>
		<h:outputText value="#{passerExamenManagedBean.questionActuelle.question}" title="#{bundle.ViewQuestionsTitle_question}"/>
		<h:outputText value="#{bundle.ViewQuestionsLabel_consigne}"/>
		<h:outputText value="#{passerExamenManagedBean.questionActuelle.consigne}" title="#{bundle.ViewQuestionsTitle_consigne}"/>
	    </p:panelGrid>

	 

	</h:form>
    </h:body>
</html>

Examen-war/web/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><ui:insert name="title">Default Title</ui:insert></title>
        <h:outputStylesheet library="css" name="jsfcrud.css"/>
    </h:head>

    <h:body>
        <h:form>
            <p:tabMenu>
                <p:menuitem><a href="/Examen-war/faces/jsf/etudiants/List.xhtml">Etudiants</a></p:menuitem>
                <p:menuitem><a href="/Examen-war/faces/jsf/examens/List.xhtml">Examens</a></p:menuitem>
                <p:menuitem><a href="/Examen-war/faces/jsf/questions/List.xhtml">Questions</a></p:menuitem>
                <p:menuitem><a href="/Examen-war/faces/jsf/reponses/List.xhtml">Reponses</a></p:menuitem>
            </p:tabMenu>
        </h:form>

        <h1>
            <ui:insert name="title">Default Title</ui:insert>
        </h1>
        <p>
            <ui:insert name="body">Default Body</ui:insert>
        </p>
    </h:body>

</html>